//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcrossReportDesigner.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcrossReportDesigner.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   言語を追加.. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang_Add {
            get {
                return ResourceManager.GetString("Lang_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未翻訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang_NotTranslated {
            get {
                return ResourceManager.GetString("Lang_NotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang_Panel_Title {
            get {
                return ResourceManager.GetString("Lang_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang_Preview {
            get {
                return ResourceManager.GetString("Lang_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Props_Height {
            get {
                return ResourceManager.GetString("Props_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Props_Position {
            get {
                return ResourceManager.GetString("Props_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幅 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Props_Width {
            get {
                return ResourceManager.GetString("Props_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_New {
            get {
                return ResourceManager.GetString("Toolbar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Open {
            get {
                return ResourceManager.GetString("Toolbar_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Toolbar_Save {
            get {
                return ResourceManager.GetString("Toolbar_Save", resourceCulture);
            }
        }
    }
}
